source 'https://rubygems.org'
gem 'rails', '4.1.4'
gem 'sqlite3'
gem 'pg'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'angularjs-rails', '~> 1.2.25'
gem 'bootstrap-sass', '~> 3.2.0.2'
gem 'jbuilder', '~> 2.0'
gem 'heroku'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'spring',        group: :development